version: '3.8'

services:
  mysql-curriculum-skill:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    container_name: mysql-curriculum-skill
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillcrawl
      API_TRACKER_BASE_URL: https://skillab-tracker.csd.auth.gr/api
      API_SKILL_EXTRACTOR_BASE_URL: https://portal.skillab-project.eu/esco-skill-extractor
    ports:
      - "5003:3306"
    volumes:
      - curriculum-skills_mysql:/var/lib/mysql
    labels:
      io.portainer.accesscontrol.teams: skillab-all
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  fastapi-service:
    depends_on:
      mysql-curriculum-skill:
        condition: service_healthy
    container_name: curriculum-skills
    build: .
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:20250819
    ports:
      - "5002:8000"
    volumes:
      - ./curriculum:/app/curriculum
      - ./crawler_json:/app/crawler_json
      - ./world_universities_and_domains.json:/mnt/data/world_universities_and_domains.json:ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_WORKERS=1
      - DB_HOST=mysql-curriculum-skill
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=skillcrawl
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/curriculum-skills/health >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      io.portainer.accesscontrol.teams: skillab-all

volumes:
  curriculum-skills_mysql:
    labels:
      io.portainer.accesscontrol.teams: skillab-all
