site_name: SKILLAB Universities Curriculum
repo_url: https://github.com/skillab-project/curriculum-skills

nav:
  - General Info: 'index.md'
  - Installation: 'installation.md'
  - Testing: 'testing.md'